const fs = require('fs');
let html = fs.readFileSync('index.html', 'utf8');

// 1. Remove Compare Mode button and div
html = html.replace(/<div style="position: absolute; top: 15px; right: 15px;">[\s\S]*?<\/button>\s*<\/div>/, '');
html = html.replace(/<!-- Compare Mode -->[\s\S]*?<!-- Standard Mode -->/g, '<!-- Standard Mode -->');
// Actually, let's just use regex to remove the specific parts
html = html.replace(/<div id="pobCompareMode"[\s\S]*?<\/div>\s*<\/div>\s*<\/div>/, '');

// Clean up the sentence
html = html.replace('View historical Personnel On Board snapshots or compare two dates.', 'View historical Personnel On Board snapshots for any past date.');

// 2. Update printPobReport function for a professional look
const oldPrintFuncRegex = /function printPobReport\(\) \{[\s\S]*?\}\s*\/\/ Ensure today's field is prepopulated/;
const newPrintFunc = `function printPobReport() {
        const dateStr = document.getElementById('pobDateValue').innerText;
        const total = document.getElementById('pobTotalValue').innerText;
        let printContents = document.getElementById('pobTable').outerHTML;
        
        let printWindow = window.open('', '', 'height=800,width=1000');
        printWindow.document.write(\`
            <html>
            <head>
                <title>POB Archive Report - \${dateStr}</title>
                <style>
                    body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #1e293b; background: #fff; }
                    .header { text-align: center; margin-bottom: 30px; border-bottom: 3px solid #10b981; padding-bottom: 20px; }
                    .header h1 { color: #0f172a; margin: 0 0 10px 0; font-size: 28px; text-transform: uppercase; letter-spacing: 1px; }
                    .header h2 { color: #10b981; margin: 0 0 15px 0; font-size: 20px; }
                    .meta-info { display: flex; justify-content: space-between; font-size: 14px; color: #475569; font-weight: bold; background: #f8fafc; padding: 15px; border-radius: 8px; margin-bottom: 20px; border: 1px solid #e2e8f0; }
                    table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 14px; }
                    th, td { border: 1px solid #cbd5e1; padding: 12px; text-align: left; }
                    th { background-color: #10b981; color: white; font-weight: bold; text-transform: uppercase; font-size: 13px; }
                    tr:nth-child(even) { background-color: #f8fafc; }
                    .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 20px; }
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>PetroMasila - BLK53</h1>
                    <h2>Personnel On Board (POB) Archive Report</h2>
                </div>
                
                <div class="meta-info">
                    <div>📅 Snapshot Date: <strong>\${dateStr}</strong></div>
                    <div>👥 Total POB: <strong>\${total} Personnel</strong></div>
                    <div>⏱️ Printed On: <strong>\${new Date().toLocaleString('en-GB')}</strong></div>
                </div>

                \${printContents}
                
                <div class="footer">
                    Generated by HR-BLK53 System &copy; \${new Date().getFullYear()} PetroMasila
                </div>
            </body>
            </html>
        \`);
        printWindow.document.close();
        printWindow.focus();
        setTimeout(() => {
            printWindow.print();
            printWindow.close();
        }, 500);
    }

    // Ensure today's field is prepopulated`;

if(html.match(oldPrintFuncRegex)) {
    html = html.replace(oldPrintFuncRegex, newPrintFunc);
}

fs.writeFileSync('index.html', html);
console.log("Updated UI and Print function.");
